runtime:
  jdbcUrl: "${db.jdbc.url}"
  jdbcUsername: "${db.username}"
  jdbcPassword: "${db.password}"
  outputDir: "${jeg.outputDir}"
  metadataOutputDir: "${jeg.outputDir}"
schemaPattern: ${db.schema}
packages:
  dev.aulait.jeg.core.domain.mastertran:
    - master
    - transaction
    - composite_master
    - composite_transaction
  dev.aulait.jeg.core.domain.parentchild:
    - parent
    - child
    - composite_parent
    - composite_child
  dev.aulait.jeg.core.domain.multifk:
    - multifk_parent
    - multifk_child
  dev.aulait.jeg.core.domain.manytomany:
    - left
    - right
  dev.aulait.jeg.core.domain.datatypes:
    - data_types
baseClassDefs:
  - tables:
      - composite_master
      - composite_parent
      - composite_child
    baseClass: dev.aulait.jeg.core.domain.CompositeBaseEntity
  - tables:
      - "*"
    baseClass: dev.aulait.jeg.core.domain.BaseEntity
annotationDefs:
  uuid:
    type: jakarta.persistence.GeneratedValue
    attributes:
      strategy: jakarta.persistence.GenerationType.UUID
  noEffect:
    type: lombok.Setter
excludedTables:
  - flyway_schema_history
excludedColmuns:
  - version
  - created_by
  - created_date
  - updated_by
  - updated_date
