runtime:
  jdbcUrl: "${db.jdbc.url}"
  jdbcUsername: "${db.username}"
  jdbcPassword: "${db.password}"
  outputDir: "${jeg.outputDir}"
  metadataOutputDir: "${jeg.outputDir}"
schemaPattern: ${db.schema}
packages:
  dev.aulait.jeg.core.domain.mastertran:
    - master
    - transaction
    - composite_master
    - composite_transaction
  dev.aulait.jeg.core.domain.parentchild:
    - parent
    - child
    - composite_parent
    - composite_child
  dev.aulait.jeg.core.domain.multifk:
    - multifk_parent
    - multifk_child
  dev.aulait.jeg.core.domain.manytomany:
    - left
    - right
  dev.aulait.jeg.core.domain.main:
    - main
    - composite_main
    - self_ref
  dev.aulait.jeg.core.domain.rel:
    - one_to_one
    - one_to_many
    - main_child
    - many_to_one
    - many_to_many
    - main_many_to_many_rel
    - composite_one_to_many
baseClassDefs:
  - tables:
      - main_child
      - composite_main
      - composite_master
      - composite_parent
      - composite_child
    baseClass: dev.aulait.jeg.core.domain.CompositeBaseEntity
  - tables:
      - "*"
    baseClass: dev.aulait.jeg.core.domain.BaseEntity
annotationDefs:
  uuid:
    type: jakarta.persistence.GeneratedValue
    attributes:
      strategy: jakarta.persistence.GenerationType.UUID
  noEffect:
    type: lombok.Setter
annotatedCols:
  main.id:
    - uuid
  MainEntity.oneToOne:
    - noEffect
  MainEntity.oneToManies:
    - noEffect
  ManyToManyEntity.mains:
    - noEffect
  OneToManyEntity.main:
    - noEffect
cascades:
  main:
    one_to_many.main_id:
      - ALL
    one_to_one.id:
      - ALL
excludedTables:
  - flyway_schema_history
excludedColmuns:
  - version
  - created_by
  - created_date
  - updated_by
  - updated_date
